# Dependabot - Automatic Dependency Package Management
version: 2
updates:

  # Maintain dependencies for Pipenv
  - package-ecosystem: "pipenv"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "development"
