---
version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:develop
    # Add additional MGM dependencies
    build:
      context: .
      dockerfile: "./docker/Dockerfile.MoniGoMani"
    restart: unless-stopped
    container_name: Freqtrade-MoniGoMani
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./user_data:/freqtrade/user_data"
      - "./user_data/logs/:/freqtrade/user_data/logs/"
      - "./user_data/mgm_pair_lists/:/freqtrade/user_data/mgm_pair_lists/"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/latest/rest-api/ documentation
    # before enabling this.
    ports:
      - "8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3-MoniGoMani_v0.13.0.sqlite
      --config /freqtrade/user_data/mgm-config.json
      --config /freqtrade/user_data/mgm-config-private.json
      --strategy MoniGoManiHyperStrategy