docs_check:
runs-on: ubuntu-20.04
steps:
- uses: actions/checkout@v2

- name: Set up Python
    uses: actions/setup-python@v2
    with:
      python-version: 3.8

  - name: Documentation build
    run: |
      pip install -r Documentation/requirements-docs.txt
      pip install mkdocs
      mkdocs build
